# By default, enable all rules provided by the linter
default: true

# Code blocks should be surrounded by blank lines
MD031: false

# Multiple consecutive blank lines
MD012: false

# Headings should be surrounded by blank lines
MD022: false

# Bad list indentation
MD007: false

# Lists should be surrounded by blank lines
MD032: false

# First line should be a h1
MD041: false

# No trailing punctuation in headings
MD026: false

# Line length
MD013:
  # Set the maximum allowed line length
  line_length: 120
  # Disable the check for specific elements that frequently exceed the limit
  code_blocks: false
  tables: false
  headings: false
